name: upnp-server
version: 0.1.0
summary: upload files with WebDAV and serve them via DLNA/UPnP
description: very minimal UPnP/DLNA server that allows uploads via WebDAV
confinement: strict

apps:
  minidlna:
    command: run-minidlna
    daemon: simple
    plugs: [network, network-bind]
  webdav:
    command: run-lighthttpd
    daemon: simple
    plugs: [network, network-bind]

parts:
  minidlna:
    source: ./minidlna
    plugin: make
    build-packages:
        - autoconf
        - automake
        - autopoint
        - autotools-dev
        - gcc-5
        - gettext
        - git
        - libavcodec-dev
        - libavformat-dev
        - libavutil-dev
        - libexif-dev
        - libflac-dev
        - libid3tag0-dev
        - libjpeg-dev
        - libogg-dev
        - libsqlite3-dev
        - libvorbis-dev
  copy:
    plugin: copy
    files:
      run-minidlna: run-minidlna
      run-lighthttpd: run-lighthttpd
      config.sh: config.sh
      default.yaml: default.yaml
    stage-packages:
        - gawk
        - libavformat-ffmpeg56
        - libc-bin
        - libexif12
        - libflac8
        - libid3tag0
        - libjpeg8
        - libstdc++6
        - libuuid1
        - libvorbisfile3
        - lighttpd-mod-webdav
        - locales
    after: [minidlna]
    stage: [-usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6]
  sqlite:
    source: ./sqlite
    plugin: make
    build-packages:
        - gzip
        - tar
        - wget
    after: [copy]
